[file-build]
# 文件名可能包含空格，所以用双引号
command:c=gcc -Wall "$(VIM_FILEPATH)" -o "$(VIM_PATHNOEXT)"
command:cpp=g++ -Wall "$(VIM_FILEPATH)" -o "$(VIM_PATHNOEXT)"
command:java=javac "$(VIM_FILENAME)"
command:go=go build -o "$(VIM_PATHNOEXT)" "$(VIM_FILEPATH)"
command:make=make -f "$(VIM_FILEPATH)"
errorformat=%+A\ %#%f\ %#(%l\\\,%c):\ %m,%C%m
output=quickfix
cwd=$(VIM_FILEDIR)
# 运行前保存所有改动的文件
save=2

[file-run]
command="$(VIM_FILEPATH)"
command:c,cpp="$(VIM_PATHNOEXT)"
command:java=java "$(VIM_FILENOEXT)"
command:go="$(VIM_PATHNOEXT)"
command:python=python "$(VIM_FILEPATH)"
command:javascript,typescript=node "$(VIM_FILEPATH)"
command:sh=bash "$(VIM_FILEPATH)"
command:lua=lua "$(VIM_FILEPATH)"
command:perl=perl "$(VIM_FILEPATH)"
command:ruby=ruby "$(VIM_FILEPATH)"
output=terminal


[project-build]
command=make
# 设置在当前项目的根目录处运行 make
cwd=$(VIM_ROOT)
errorformat=%+A\ %#%f\ %#(%l\\\,%c):\ %m,%C%m

[project-run]
command=make run
# <root> 是 $(VIM_ROOT) 的别名，写起来容易些
cwd=<root>
output=terminal
