[file-build]
# use double quotes to avoid space problem
command:c=clang -Wall "$(VIM_FILEPATH)" -o "$(VIM_PATHNOEXT)"
command:cpp=clang++ -Wall "$(VIM_FILEPATH)" -o "$(VIM_PATHNOEXT)"
command:go=go build -o "$(VIM_PATHNOEXT)" "$(VIM_FILEPATH)"
command:java=javac "$(VIM_FILENAME)"
command:make=make -f "$(VIM_FILEPATH)"
errorformat=%+A\ %#%f\ %#(%l\\\,%c):\ %m,%C%m
output=quickfix
cwd=$(VIM_FILEDIR)
# save all modified buffer before execute
save=2

[file-run]
command="$(VIM_FILEPATH)"
command:c,cpp="$(VIM_PATHNOEXT)"
command:go="$(VIM_PATHNOEXT)"
command:java=java "$(VIM_FILENOEXT)"
command:javascript,typescript=node "$(VIM_FILEPATH)"
command:lua=lua "$(VIM_FILEPATH)"
command:perl=perl "$(VIM_FILEPATH)"
command:python=python "$(VIM_FILEPATH)"
command:ruby=ruby "$(VIM_FILEPATH)"
command:sh=bash "$(VIM_FILEPATH)"
output=terminal


[project-build]
command=make
# run make under cwd root
cwd=$(VIM_ROOT)
errorformat=%+A\ %#%f\ %#(%l\\\,%c):\ %m,%C%m

[project-run]
command=make run
# <root> is an alias of $(VIM_ROOT)
cwd=<root>
output=terminal
